on:
    push:
        branches:
            - {{cookiecutter.github_default_branch}}
    pull_request:
        branches:
            - {{cookiecutter.github_default_branch}}
{% raw %}
name: macOS build
jobs:
    test-macOS:
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.os }} (${{ matrix.python-version}})
        strategy:
            fail-fast: false
            matrix:
              os: ["macOS-latest"]
              python-version: ["3.10"]
        steps:
            - uses: conda-incubator/setup-miniconda@v2
              with:
                auto-activate-base: true
                python-version: ${{ matrix.python-version }}
            - name: Install GDAL
              run: conda install -c conda-forge gdal --yes
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
                  pip install .
{% endraw %}